export const randomData = [
  {
    id: "1",
    name: "Alice Johnson",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    chat: "Hey, did you see the latest update on the project?",
    date: "10:00 PM",
    email: "abc@gmail.com",
    chatData: ["aaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "2",
    name: "Bob Smith",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    chat: "I have some new ideas for the marketing campaign.",
    date: "10:00 PM",
    email: "def@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "3",
    name: "Carol Lee",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    chat: "Can you send me the report by end of day?",
    date: "10:00 PM",
    email: "front  @gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "4",
    name: "David Brown",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    chat: "Looking forward to our meeting tomorrow.",
    date: "10:00 PM",
    email: "ab3w4c@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "5",
    name: "Emily Davis",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    chat: "Let's catch up later this week!",
    date: "10:00 PM",
    email: "ab33gvc@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "6",
    name: "Franklin Wilson",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
    chat: "Did you get a chance to review the draft?",
    date: "10:00 PM",
    email: "abc@rtergmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "7",
    name: "Grace Adams",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
    chat: "Can you help with the presentation slides?",
    date: "10:00 PM",
    email: "abfdfcc@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00", "10:00"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "8",
    name: "Henry Carter",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    chat: "The server issue has been resolved.",
    date: "10:00 PM",
    email: "fffbc@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "9",
    name: "Isabella Clark",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    chat: "Let's schedule a call to discuss the new features.",
    date: "10:00 PM",
    email: "absdwssc@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "10",
    name: "Jack Martinez",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
    chat: "Can we push the deadline to next week?",
    date: "10:00 PM",
    email: "abcssdf@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "11",
    name: "Katherine Turner",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
    chat: "I'll be out of the office for the next two days.",
    date: "10:00 PM",
    email: "abc@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "12",
    name: "Liam Harris",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    chat: "I need the budget report by tomorrow.",
    date: "10:00 PM",
    email: "afffbc@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "13",
    name: "Mia Young",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    chat: "The team needs your feedback on the design.",
    date: "10:00 PM",
    email: "abcrrtg@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "14",
    name: "Noah Walker",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
    chat: "Can we arrange a training session next week?",
    date: "10:00 PM",
    email: "abcyuiug@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "15",
    name: "Olivia Scott",
    image: "https://randomuser.me/api/portraits/women/11.jpg",
    chat: "I have updated the project plan.",
    date: "10:00 PM",
    email: "abgv23c@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "16",
    name: "Paul Allen",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    chat: "Let's finalize the contract details soon.",
    date: "10:00 PM",
    email: "abcknb@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "17",
    name: "Quinn Green",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    chat: "Please review the attached document.",
    date: "10:00 PM",
    email: "abfdc@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "18",
    name: "Ryan King",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
    chat: "Can we discuss the new project scope?",
    date: "10:00 PM",
    email: "abcfdsd@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "19",
    name: "Sophia Baker",
    image: "https://randomuser.me/api/portraits/women/13.jpg",
    chat: "The client meeting went well today.",
    date: "10:00 PM",
    email: "aaabc@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "20",
    name: "Thomas Lewis",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
    chat: "I will send over the revised estimates shortly.",
    date: "10:00 PM",
    email: "ui@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "21",
    name: "Uma Patel",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
    chat: "The new feature is ready for testing.",
    date: "10:00 PM",
    email: "dec@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
  {
    id: "22",
    name: "Victor Nelson",
    image: "https://randomuser.me/api/portraits/men/14.jpg",
    chat: "Please confirm the meeting time.",
    date: "10:00 PM",
    email: "dev@gmail.com",
    chatData: ["aaaa", "bbbb"],
    chatTime: ["10:00 pm", "10:00 pm"],
    statusTime: "Yesterday 10:00pm",
    imageArray: [
      "https://randomuser.me/api/portraits/men/21.jpg",
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/men/23.jpg",
      "https://randomuser.me/api/portraits/men/24.jpg",
      "https://randomuser.me/api/portraits/men/25.jpg",
    ],
  },
];
